// Development-only visual fixtures. Never imported by a production build.
export const categories = [
  ["fashion", "Fashion", "fashion", ["Size", "Colour", "Material"]],
  [
    "mobiles",
    "Mobiles",
    "electronics",
    ["Brand", "Model", "Storage", "Warranty"],
  ],
  [
    "vehicles",
    "Vehicles",
    "vehicles",
    ["Make", "Model", "Year", "Kilometres", "Fuel"],
  ],
  ["home", "Home & furniture", "general", ["Material", "Dimensions"]],
  ["electronics", "Electronics", "electronics", ["Brand", "Model"]],
  ["services", "Services", "general", ["Service area", "Price unit"]],
  ["property", "Property", "general", ["Area", "Bedrooms"]],
  ["bicycles", "Bicycles", "vehicles", ["Brand", "Frame size"]],
].map(([id, name, theme, fields], i) => ({
  id,
  name,
  theme,
  fields,
  position: i,
  active: true,
}));
export const plans = [
  ["free", "Free", 0, 3],
  ["starter", "Starter", 500, 50],
  ["growth", "Growth", 1000, 250],
  ["business", "Business", 2000, 1000],
  ["catalogue", "Large catalogue", 5000, 15000],
].map(([id, name, price, listing_limit]) => ({
  id,
  name,
  price,
  listing_limit,
  active: true,
}));
export const settings = {
  name: "Leikai Market",
  tagline: "Our people. Our neighbourhood.",
  hero_title: "Your neighbourhood. Every shop.",
  hero_description:
    "A little closer. A little more local. Discover great finds from the people and shops around you.",
  hero_image: "/images/hero-handloom.webp",
  announcement: "Made for Manipur. Open to everyone.",
  support_whatsapp: "",
  support_email: "",
  ads_price_note: "Get in touch for featured placement prices.",
};
export const sellers = [
  {
    id: "sample-handlooms",
    name: "Leikai Handlooms",
    slug: "leikai-handlooms",
    theme: "fashion",
    type: "shop",
    location: "Khurai, Imphal",
    cover: "/images/hero-handloom.webp",
    description:
      "Woven with care. Discover traditional phanek, shawls and everyday textiles from local makers.",
    socials: {},
    whatsapp: "",
  },
  {
    id: "sample-mobiles",
    name: "Mobile Planet",
    slug: "mobile-planet",
    theme: "electronics",
    type: "shop",
    location: "Keishampat, Imphal",
    cover: "/images/phone.jpg",
    description: "Phones, accessories and everyday technology, close to home.",
    socials: {},
    whatsapp: "",
  },
  {
    id: "sample-motors",
    name: "Imphal Motors",
    slug: "imphal-motors",
    theme: "vehicles",
    type: "shop",
    location: "Thangal Bazaar, Imphal",
    cover: "/images/car.jpg",
    description:
      "Explore local cars and two-wheelers. Contact us to arrange a viewing.",
    socials: {},
    whatsapp: "",
  },
  {
    id: "sample-home",
    name: "HomeHome Imphal",
    slug: "homehome-imphal",
    theme: "general",
    type: "shop",
    location: "Uripok, Imphal",
    cover: "/images/chair.jpg",
    description: "Considered pieces for the place you call home.",
    socials: {},
    whatsapp: "",
  },
];
export const listings = [
  [
    "sample-1",
    "iPhone · 128 GB",
    39900,
    "mobiles",
    "phone.jpg",
    1,
    "Used",
    { Brand: "Apple", Storage: "128 GB" },
  ],
  [
    "sample-2",
    "Handwoven Manipuri Phanek",
    2850,
    "fashion",
    "phanek.webp",
    0,
    "New",
    { Material: "Cotton", Colour: "Magenta" },
  ],
  [
    "sample-3",
    "Pre-owned sports coupe",
    3250000,
    "vehicles",
    "car.jpg",
    2,
    "Used",
    { Year: "2019", Fuel: "Petrol" },
  ],
  [
    "sample-4",
    "Natural wood stool",
    6800,
    "home",
    "chair.jpg",
    3,
    "New",
    { Material: "Solid wood" },
  ],
  [
    "sample-5",
    "Everyday over-ear headphones",
    2490,
    "electronics",
    "headphones.jpg",
    1,
    "New",
    { Brand: "Local collection" },
  ],
  [
    "sample-6",
    "The weekend edit",
    1450,
    "fashion",
    "fashion.jpg",
    0,
    "New",
    { Size: "S–XL" },
  ],
].map(([id, title, price, category_id, img, si, condition, attributes]) => ({
  id,
  title,
  price,
  category_id,
  images: ["/images/" + img],
  seller_id: sellers[si].id,
  seller: sellers[si],
  location: sellers[si].location,
  condition,
  attributes,
  description:
    "Visit the seller to learn more about this item, availability and collection options.",
  status: "published",
  socials: {},
  tags: "",
  created_at: "2026-10-03T04:00:00Z",
}));
